# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - miAppServices-Click-counter

on:
  push:
    branches:
      - produccion
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Instalando dependencias
      run: npm install

    - name: Construyendo proyecto Build
      if: github.event_name == 'push'
      run: npm run build

    - name: Subiendo build folder
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: /home/site/wwwroot/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'miAppServices-Click-counter'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc9d9c3a58e249d3b922c9242b36556d }}
        package: .